### ISSUE TITLE
No Longer Works in Anaconda

### ISSUE THREAD

**Issue by kjkoeller** [adrn/pyia#15]
The package can no longer be installed on Windows due to dustmap dependency on Healpy which does not support windows at all. Something changed with version 1.3 and 1.4 where Healpy is now required to be installed but before a few months ago it was not.

**Comment by adrn** [comment]
Thanks for reporting! I'll remove the explicit dependency and add it back in as an optional dependency, and release a new version. Sorry about the hassle!

**Comment by kjkoeller** [comment]
Do you have a timeline for when you might release a new update?

**Comment by adrn** [comment]
I'm planning to get to it this weekend! Shouldn't take long once I have an hour to focus on this, but this week has been 🔥...

**Comment by kjkoeller** [comment]
So the real error is coming from your dependency on dustmaps (https://github.com/gregreen/dustmaps). So I will move the issue to them since they require healpy.

**Comment by adrn** [comment]
I just released v1.4.1, which makes `dustmaps` an optional dependency again. That should be on pypi soon!

**Comment by kjkoeller** [comment]
That fixed the issue, thanks so much for fixing it. It's greatly appreciated!
